### ISSUE TITLE
Create API Endpoints

### ISSUE THREAD

**Issue by hasanhaja** [HRahimy/positive_affirmations#14]
## Todo

> Incomplete task list. Update todo with remaining tasks.

- [ ] Create members endpoint
  - [ ] GET
  - [ ] POST
  - [ ] PUT
  - [ ] PATCH
- [ ] Create files endpoint
  - [ ] Post
  - [ ] Patch   

## Notes to self

- [ ] Explore articles related to CQRS and familiarize self with that pattern 
- [ ] Explore NestJS more
