### ISSUE TITLE
Implement account setup screens in mobile app

### ISSUE THREAD

**Issue by spiceFlowMatrix** [HRahimy/positive_affirmations#3]
### New feature specification

**Name:** Account setup

- Submit name
- Submit nickname (optional)
   User can cancel and go back to name submission
- View application summary.
   - User can cancel and go back to nickname submission
   - User can skip

#### TODO @HRahimy 

- [x] Add tests for name form
- [x] Implement name form UI with state
- [ ] Add tests for nickName form models and bloc
- [ ] Implement models and bloc for nickName form
- [ ] Add tests for nickName form UI
- [ ] Implement nickName form UI
- [ ] Add tests for app summary UI
- [ ] Implement app summary UI
