### ISSUE TITLE
Add affirmation screens

### ISSUE THREAD

**Issue by spiceFlowMatrix** [HRahimy/positive_affirmations#6]
### TODOs @HRahimy 

- [ ] Write tests for Affirmations listing bloc
- [ ] Add affirmations listing bloc
- [ ] Write tests for Affirmations listing UI
- [ ] Add Affirmations listing UI
