### ISSUE TITLE
Create entities for backend

### ISSUE THREAD

**Issue by hasanhaja** [HRahimy/positive_affirmations#7]
## Todo
- [ ] Update Affirmation entity to have a deactivated to match the UI
- [x] Create entities for the application somewhat following clean architecture principles
    - [x] User
    - [x] Letter
    - [x] Photo
    - [x] Affirmation
    - [x] Like
- [x] Add `archive` as a field in the entities
- [x] Add constructors with all field for all entities
- [x] Split entities from `users` module to it's own respective modules
- [x] Wire up `TypeORMModule` and run it locally to see how the entities create tables
    - [x] Setup database and auth correctly 
    - [x] Resolve `Error: Column "reactionType" of Entity "ReactionEntity" is defined as enum, but missing "enum" or "enumName" properties.`
- [x] Rename `LikeEntitity` to `ReactionEntity`
- [x] Create separate `Note`, `Font` and `Stamp` entities
- [x] Include Time Created field

## Notes to self

- [x] Think about how to split the entities  
- [ ] Explore cascades on one-to-many relationships
- [ ] Will the schema require anything else for bucket configuration?
- [ ] Speak to Hamza about CQRS and if that's something we need to think about at this stage
- [x] Where to store interfaces?
- [x] Use this as a starting point: [github.com/HRahimy/showcasejs](https://github.com/HRahimy/showcasejs/tree/user_profile/apps/api/src/app/users)
- [ ] Verify constructors especially `UserEntity` which calls things like `AffirmationEntity` which also calls `ReaffirmationEnttity`
    - [ ] How can you construct `UserEntity` with `AffirmationEntity` and things like that? Should it be null? 
- [ ] Think about creating the next issue to specify when the database and things are set up
